sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t shinandmin/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true shinandmin/docker-react-app npm run test -- --coverage

deploy:
  provider: elastickbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-623280994414"
  bucket_path: "docker-react-app"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key_id: $AWS_SECRET_ACCESS_KEY
